name: Multi-Stage CI/CD Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      mode:
        description: "deploy or rollback"
        required: true
        type: choice
        default: deploy
        options:
          - deploy
          - rollback

      rollback_tag:
        description: "Rollback release tag (example: v1.0.10)"
        required: false
        type: string

env:
  BUILD_CONFIG: Release

permissions:
  contents: write
  id-token: write

#########################################################
# STAGE 1 - BUILD (ONLY ONCE)
#########################################################

jobs:

  build:
    if:  github.ref == 'refs/heads/master'
    # if: github.event_name == 'push'

    runs-on: ubuntu-latest

    outputs:
      artifact_name: functions.zip

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ${{ secrets.SOLUTIONFILE }}

      - name: Build
        run: dotnet build ${{ secrets.SOLUTIONFILE }} --configuration $BUILD_CONFIG --no-restore

      - name: Publish Function
        run: |
          dotnet publish ${{ secrets.PUBLISHFUNCTIONS }} \
            --configuration $BUILD_CONFIG \
            --no-build \
            --output ${{ github.workspace }}/publish

      - name: Create ZIP artifact
        run: |
          cd ${{ github.workspace }}/publish
          zip -r ${{ github.workspace }}/functions.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functions-artifact
          path: functions.zip

#########################################################
# STAGE 2 - CREATE RELEASE (VERSIONING)
#########################################################

  release:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functions-artifact
        

      - name: Generate version tag
        id: tag
        run: |
          TAG="v1.0.${{ github.run_number }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

          
      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}

      - name: Create GitHub Release
        id: release
        uses: actions/github-script@v9.0.0
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: functions.zip
          generate_release_notes: true

#########################################################
# STAGE 3 - DEPLOY PROD (FROM SAME ARTIFACT)
#########################################################

  deployProd:

    needs: build
    runs-on: ubuntu-latest

    environment: PROD

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functions-artifact

#########################################################
# STAGE 4 - ROLLBACK (NO BUILD, ONLY RELEASE ARTIFACT)
#########################################################

  rollbackProd:

    if: github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'rollback'

    runs-on: ubuntu-latest

    environment: PROD

    steps:

      - name: Validate rollback tag
        run: |
          if [ -z "${{ github.event.inputs.rollback_tag }}" ]; then
            echo "rollback_tag required"
            exit 1
          fi

      - name: Download release artifact
        id: download
        uses: actions/github-script@v9.0.0
        with:
          tag: ${{ github.event.inputs.rollback_tag }}
          fileName: functions.zip

      - name: Deploy rollback version
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.PRD_FUNCAPP_NAME }}
          package: functions.zip
