name: SIT

on:
  push:
    branches:
      - develop
      - release
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      environment: ${{ github.ref == 'refs/heads/master' && 'DEV' || github.ref == 'refs/heads/uat' && 'UAT' || 'PRD' }}
      serviceConnection: ${{ github.ref == 'refs/heads/master' && '${{ secrets.DEV_SERVICE_CONNECTION }}' || github.ref == 'refs/heads/uat' && '${{ secrets.UAT_SERVICE_CONNECTION }}'  || '${{ secrets.PRD_SERVICE_CONNECTION }}' }}
      functionsAppName: ${{ github.ref == 'refs/heads/master' && 'devtestfnc' || github.ref == 'refs/heads/uat' && 'uattestfnc' || 'prdtestfnc' }}
      dbServerName: ${{ github.ref == 'refs/heads/master' && 'devdbserver00' || github.ref == 'refs/heads/uat' && 'uatdbserver00' || 'prddbserver00' }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets[env.serviceConnection] }}

    - name: Stop Functions
      run: |
        az functionapp stop --name ${{ env.functionsAppName }} --resource-group <resource-group-name>
    
    - name: Deploy Functions
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.functionsAppName }}
        package: '$(Pipeline.Workspace)/SSET/Functions/Functions.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Start Functions
      run: |
        az functionapp start --name ${{ env.functionsAppName }} --resource-group <resource-group-name>

    - name: Deploy Front End
      run: |
        choco install azcopy10
        azcopy copy $(Pipeline.Workspace)\SSET\Front\*.js 'https://$(storageName).blob.core.windows.net/$web$(websiteStorageSasToken)' --content-type="application/javascript; charset=utf8"
        azcopy sync $(Pipeline.Workspace)\SSET\Front 'https://$(storageName).blob.core.windows.net/$web$(websiteStorageSasToken)' --delete-destination=true

    - name: Check Front End
      run: |
        $response = Invoke-WebRequest -Uri $(websiteUrl)index.html -Method Head
        if ($response.StatusCode -ne 200) {
          throw
        }
      shell: pwsh
      continue-on-error: true

    - name: Deploy to SQL Database
      run: |
        sqlcmd -S <server-name> -d <database-name> -U <username> -P <password> -i path/to/your/sql/scripts.sql
