name: SIT

on:
  push:
    branches:
      - develop
      - release
      - master

env:
  DEV_ENVIRONMENT: DEV
  DEV_SERVICE_CONNECTION: ${{ secrets. AZURE_CREDENTIALS }}
  DEV_FUNCTIONS_APP_NAME: devtestfnc
  UAT_ENVIRONMENT: UAT
  UAT_SERVICE_CONNECTION: ${{ secrets. AZURE_CREDENTIALS }}
  UAT_FUNCTIONS_APP_NAME: uattestfnc
  PRD_SERVICE_CONNECTION: ${{ secrets. AZURE_CREDENTIALS }}
  DEV_SQL_DB: devdbserver00
  UAT_SQL_DB: uatdbserver00
  PRD_SQL_DB: prddbserver00
  PRD_ENVIRONMENT: PRD

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/uat'
    env:
      environment: ${{ github.ref == 'refs/heads/master' && env.DEV_ENVIRONMENT || github.ref == 'refs/heads/uat' && env.UAT_ENVIRONMENT || env.PRD_ENVIRONMENT }}
      serviceConnection: ${{ github.ref == 'refs/heads/master' && env.DEV_SERVICE_CONNECTION || github.ref == 'refs/heads/uat' && env.UAT_SERVICE_CONNECTION || env.PRD_SERVICE_CONNECTION }}
      functionsAppName: ${{ github.ref == 'refs/heads/master' && env.DEV_FUNCTIONS_APP_NAME || github.ref == 'refs/heads/uat' && env.UAT_FUNCTIONS_APP_NAME || env.PRD_FUNCTIONS_APP_NAME }}
      dbServerName: ${{ github.ref == 'refs/heads/master' && env.DEV_SQL_DB || github.ref == 'refs/heads/uat' && env.UAT_SQL_DB || env.PRD_SQL_DB }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets[env.serviceConnection] }}
        
    - name: Stop Azure Function App
      run: az functionapp stop --name devtestfnc --resource-group testfnc_group    
